const CATS=['Mixed','General Knowledge','Geography','Science','History','Pop Culture','Animals','Food & Drink','Sports','Movies & TV','Music','Art & Literature','Technology','Space','Human Body','Languages','Finance','World Flags','World Capitals','Landmarks','Math','Fashion','Psychology','Mythology','Nature','Cars & Transport'];

const TRIVIA_BANK=[
// ── GENERAL KNOWLEDGE ──
{q:"What is the only country in the world that is also a continent?",a:"australia",c:"General Knowledge"},
{q:"How many sides does a heptagon have?",a:"7",c:"General Knowledge"},
{q:"What is the most spoken language in the world by native speakers?",a:"mandarin",alts:["chinese","mandarin chinese"],c:"General Knowledge"},
{q:"What comes after a trillion?",a:"quadrillion",c:"General Knowledge"},
{q:"How many time zones does Russia have?",a:"11",c:"General Knowledge"},
{q:"What animal has the longest lifespan?",a:"bowhead whale",alts:["ocean quahog","greenland shark"],c:"General Knowledge",h:"Can live over 200 years"},
{q:"What percentage of the Earth's surface is water?",a:"71",alts:["70","71%"],c:"General Knowledge"},
{q:"In what year did the Berlin Wall fall?",a:"1989",c:"General Knowledge"},
{q:"What is the only mammal capable of true flight?",a:"bat",c:"General Knowledge"},
{q:"How many bones does a shark have?",a:"0",alts:["zero","none"],c:"General Knowledge",h:"Their skeleton is made of cartilage"},
{q:"What is the smallest planet in our solar system?",a:"mercury",c:"General Knowledge"},
{q:"Which country produces the most coffee in the world?",a:"brazil",c:"General Knowledge"},
{q:"What is the chemical symbol for iron?",a:"fe",c:"General Knowledge"},
{q:"How many days are in a leap year?",a:"366",c:"General Knowledge"},
{q:"What organ produces insulin?",a:"pancreas",c:"General Knowledge"},
{q:"What is the world's largest religion?",a:"christianity",c:"General Knowledge"},
{q:"How many players are on a basketball team on the court?",a:"5",c:"General Knowledge"},
{q:"What country is home to the kangaroo?",a:"australia",c:"General Knowledge"},
{q:"What is the hardest natural substance on Earth?",a:"diamond",c:"General Knowledge"},
{q:"What does HTTP stand for?",a:"hypertext transfer protocol",c:"General Knowledge"},

// ── GEOGRAPHY ──
{q:"What is the capital of Brazil?",a:"brasilia",c:"Geography"},
{q:"Which is the world's longest river?",a:"nile",alts:["amazon"],c:"Geography",h:"Debate exists but Nile is traditionally accepted"},
{q:"What country has the most land borders?",a:"china",alts:["russia"],c:"Geography",h:"Both share the record at 14 countries"},
{q:"What is the deepest lake in the world?",a:"baikal",alts:["lake baikal"],c:"Geography"},
{q:"Which continent has the most countries?",a:"africa",c:"Geography"},
{q:"What is the smallest country in the world by area?",a:"vatican",alts:["vatican city"],c:"Geography"},
{q:"Through how many countries does the Amazon River flow?",a:"9",c:"Geography"},
{q:"What is the capital of Canada?",a:"ottawa",c:"Geography"},
{q:"Which ocean is the largest?",a:"pacific",c:"Geography"},
{q:"What country has the most islands?",a:"sweden",c:"Geography",h:"Over 220,000 islands"},
{q:"What is the largest country by land area?",a:"russia",c:"Geography"},
{q:"Which country has the most pyramids?",a:"sudan",c:"Geography",h:"Not Egypt — Sudan has over 200"},
{q:"The Great Barrier Reef is located off the coast of which country?",a:"australia",c:"Geography"},
{q:"What is the capital of New Zealand?",a:"wellington",c:"Geography"},
{q:"Which mountain range separates Europe from Asia?",a:"urals",alts:["ural mountains"],c:"Geography"},
{q:"What is the world's largest desert?",a:"sahara",c:"Geography"},
{q:"Which country has the longest coastline?",a:"canada",c:"Geography"},
{q:"What is the capital of Argentina?",a:"buenos aires",c:"Geography"},
{q:"The Strait of Gibraltar connects the Atlantic Ocean to which sea?",a:"mediterranean",alts:["mediterranean sea"],c:"Geography"},
{q:"What country does Greenland belong to?",a:"denmark",c:"Geography"},

// ── SCIENCE ──
{q:"What is the atomic number of carbon?",a:"6",c:"Science"},
{q:"What planet is known for its Great Red Spot?",a:"jupiter",c:"Science"},
{q:"What is the powerhouse of the cell?",a:"mitochondria",c:"Science"},
{q:"What is the speed of light in km/s (approx)?",a:"300000",alts:["299792"],c:"Science"},
{q:"What gas makes up most of Earth's atmosphere?",a:"nitrogen",c:"Science",h:"About 78%"},
{q:"What is the most abundant element in the universe?",a:"hydrogen",c:"Science"},
{q:"What is absolute zero in Celsius?",a:"-273",alts:["-273.15"],c:"Science"},
{q:"What force keeps planets in orbit around the sun?",a:"gravity",c:"Science"},
{q:"What does DNA stand for?",a:"deoxyribonucleic acid",c:"Science"},
{q:"How many chromosomes do humans have?",a:"46",c:"Science"},
{q:"What is the process by which plants make food?",a:"photosynthesis",c:"Science"},
{q:"What is the most reactive element?",a:"fluorine",alts:["cesium"],c:"Science"},
{q:"What particles are found in the nucleus of an atom?",a:"protons and neutrons",alts:["protons","neutrons"],c:"Science"},
{q:"What is the unit of electrical resistance?",a:"ohm",c:"Science"},
{q:"What is the chemical formula for water?",a:"h2o",c:"Science"},
{q:"What scientist developed the theory of relativity?",a:"einstein",alts:["albert einstein"],c:"Science"},
{q:"What is the half-life of carbon-14?",a:"5730",alts:["5730 years"],c:"Science",h:"Approximately 5,730 years"},
{q:"What is the name of the process where a solid turns directly to gas?",a:"sublimation",c:"Science"},
{q:"What planet has the strongest magnetic field in the solar system?",a:"jupiter",c:"Science"},
{q:"What is the study of fungi called?",a:"mycology",c:"Science"},

// ── HISTORY ──
{q:"In which year did World War I begin?",a:"1914",c:"History"},
{q:"Who was the first President of the United States?",a:"washington",alts:["george washington"],c:"History"},
{q:"What ancient wonder of the world was located in Alexandria?",a:"lighthouse",alts:["lighthouse of alexandria"],c:"History"},
{q:"Which empire was ruled by Genghis Khan?",a:"mongol",alts:["mongol empire"],c:"History"},
{q:"In what year did the French Revolution begin?",a:"1789",c:"History"},
{q:"What was the name of the first artificial satellite launched into space?",a:"sputnik",c:"History"},
{q:"Who discovered penicillin?",a:"alexander fleming",alts:["fleming"],c:"History"},
{q:"What was the currency of France before the Euro?",a:"franc",alts:["french franc"],c:"History"},
{q:"The Magna Carta was signed in which year?",a:"1215",c:"History"},
{q:"Which pharaoh built the Great Pyramid of Giza?",a:"khufu",alts:["cheops"],c:"History"},
{q:"What year did the Soviet Union collapse?",a:"1991",c:"History"},
{q:"Who invented the printing press?",a:"gutenberg",alts:["johannes gutenberg"],c:"History"},
{q:"What war was fought between 1950 and 1953 on the Korean peninsula?",a:"korean war",alts:["korean"],c:"History"},
{q:"Which country first gave women the right to vote?",a:"new zealand",c:"History",h:"In 1893"},
{q:"What ancient civilization built Machu Picchu?",a:"inca",alts:["incas"],c:"History"},
{q:"Who assassinated Archduke Franz Ferdinand in 1914?",a:"gavrilo princip",alts:["princip"],c:"History"},
{q:"What year did Nelson Mandela become president of South Africa?",a:"1994",c:"History"},
{q:"What was the codename for the Allied invasion of Normandy in 1944?",a:"operation overlord",alts:["overlord"],c:"History"},
{q:"Who was the last emperor of China?",a:"puyi",alts:["pu yi"],c:"History"},
{q:"The Battle of Waterloo was fought in which country?",a:"belgium",c:"History"},

// ── POP CULTURE ──
{q:"What streaming platform produced 'Stranger Things'?",a:"netflix",c:"Pop Culture"},
{q:"What is the name of Thor's hammer in Marvel?",a:"mjolnir",c:"Pop Culture"},
{q:"Which singer is known as the 'Queen of Pop'?",a:"madonna",c:"Pop Culture"},
{q:"What fictional school does Harry Potter attend?",a:"hogwarts",c:"Pop Culture"},
{q:"What color is the Grinch?",a:"green",c:"Pop Culture"},
{q:"In 'The Lion King', what is Simba's father's name?",a:"mufasa",c:"Pop Culture"},
{q:"What does BTS stand for?",a:"bangtan sonyeondan",alts:["beyond the scene","bangtan boys"],c:"Pop Culture"},
{q:"What app popularized short-form video before TikTok?",a:"vine",c:"Pop Culture"},
{q:"What fictional city does Batman protect?",a:"gotham",alts:["gotham city"],c:"Pop Culture"},
{q:"What is the highest-grossing film franchise of all time?",a:"marvel",alts:["mcu"],c:"Pop Culture"},
{q:"Who created the character Sherlock Holmes?",a:"arthur conan doyle",alts:["conan doyle"],c:"Pop Culture"},
{q:"What Pixar film features a rat who wants to be a chef?",a:"ratatouille",c:"Pop Culture"},
{q:"Which singer performed at the 2023 Super Bowl halftime show?",a:"rihanna",c:"Pop Culture"},
{q:"What does the 'K' in K-pop stand for?",a:"korean",c:"Pop Culture"},
{q:"What game features a character called 'Among Us' crewmate?",a:"among us",c:"Pop Culture"},

// ── ANIMALS ──
{q:"What is the only venomous primate?",a:"slow loris",c:"Animals"},
{q:"How many hearts does an octopus have?",a:"3",alts:["three"],c:"Animals"},
{q:"What is the gestation period of an elephant?",a:"22",alts:["22 months"],c:"Animals",h:"About 22 months — longest of any land animal"},
{q:"What is the fastest bird in the world?",a:"peregrine falcon",alts:["falcon"],c:"Animals"},
{q:"What animal has the thickest skin?",a:"whale",alts:["sperm whale","blue whale"],c:"Animals"},
{q:"How many legs does a spider have?",a:"8",alts:["eight"],c:"Animals"},
{q:"What is the only mammal that can't jump?",a:"elephant",c:"Animals"},
{q:"What animal produces the most milk globally?",a:"cow",c:"Animals"},
{q:"How many teeth does an adult human have?",a:"32",c:"Animals"},
{q:"What is a group of flamingos called?",a:"flamboyance",c:"Animals"},
{q:"What animal has the largest eyes relative to its body?",a:"tarsier",c:"Animals"},
{q:"How do sea otters sleep without drifting away?",a:"hold hands",alts:["holding hands","they hold hands"],c:"Animals",h:"They hold hands with other otters"},
{q:"What bird lays the largest egg relative to its body size?",a:"kiwi",c:"Animals"},
{q:"What is the only bird that can fly backwards?",a:"hummingbird",c:"Animals"},
{q:"What is a baby kangaroo called?",a:"joey",c:"Animals"},

// ── FOOD & DRINK ──
{q:"What is the main ingredient in guacamole?",a:"avocado",c:"Food & Drink"},
{q:"What country does kimchi originate from?",a:"korea",alts:["south korea"],c:"Food & Drink"},
{q:"What is the world's most expensive spice by weight?",a:"saffron",c:"Food & Drink"},
{q:"What type of pasta is tube-shaped?",a:"penne",alts:["rigatoni","ziti","penne"],c:"Food & Drink"},
{q:"What fruit is wine made from?",a:"grape",alts:["grapes"],c:"Food & Drink"},
{q:"What is the main protein in milk?",a:"casein",c:"Food & Drink"},
{q:"What country invented pizza?",a:"italy",c:"Food & Drink"},
{q:"What is the hottest type of chili pepper?",a:"carolina reaper",alts:["reaper"],c:"Food & Drink"},
{q:"Miso soup is a staple of which country's cuisine?",a:"japan",c:"Food & Drink"},
{q:"What grain is used to make bourbon whiskey?",a:"corn",alts:["maize"],c:"Food & Drink"},
{q:"What is the French word for 'bread'?",a:"pain",c:"Food & Drink"},
{q:"What cocktail contains vodka, ginger beer, and lime?",a:"moscow mule",c:"Food & Drink"},
{q:"What is the main ingredient in hummus?",a:"chickpeas",alts:["chickpea","garbanzo"],c:"Food & Drink"},
{q:"What type of bean is used to make tofu?",a:"soy",alts:["soybean"],c:"Food & Drink"},
{q:"What gives red wine its color?",a:"grape skins",alts:["tannins","anthocyanins"],c:"Food & Drink"},

// ── SPORTS ──
{q:"How many players are on a football (soccer) team?",a:"11",c:"Sports"},
{q:"What country has won the most FIFA World Cups?",a:"brazil",c:"Sports"},
{q:"In tennis, what is the score called when both players have 40 points?",a:"deuce",c:"Sports"},
{q:"What is the Olympic motto?",a:"faster higher stronger",alts:["citius altius fortius"],c:"Sports"},
{q:"How many rings are on the Olympic flag?",a:"5",alts:["five"],c:"Sports"},
{q:"What sport is played at Wimbledon?",a:"tennis",c:"Sports"},
{q:"How long is a marathon in kilometers?",a:"42",alts:["42.195","42.2"],c:"Sports"},
{q:"What is the highest score possible in a single bowling frame?",a:"30",alts:["30 points"],c:"Sports",h:"Three strikes in a row"},
{q:"In which country did the martial art Judo originate?",a:"japan",c:"Sports"},
{q:"What is the diameter of a basketball hoop in inches?",a:"18",alts:["18 inches"],c:"Sports"},
{q:"How many players are in a volleyball team on the court?",a:"6",alts:["six"],c:"Sports"},
{q:"What number is always opposite '1' on a die?",a:"6",c:"Sports"},
{q:"What city hosted the 2016 Summer Olympics?",a:"rio",alts:["rio de janeiro"],c:"Sports"},
{q:"In baseball, how many strikes cause a batter to be out?",a:"3",c:"Sports"},
{q:"What is the governing body of world football?",a:"fifa",c:"Sports"},

// ── MOVIES & TV ──
{q:"What 1994 film features a character named Forrest Gump?",a:"forrest gump",c:"Movies & TV"},
{q:"In 'The Godfather', what animal's head is put in the bed?",a:"horse",c:"Movies & TV"},
{q:"What film holds the record for most Academy Award wins?",a:"ben-hur",alts:["ben hur","titanic","lord of the rings"],c:"Movies & TV",h:"Ben-Hur, Titanic, and LOTR: Return of the King each won 11"},
{q:"Who played Iron Man in the MCU?",a:"robert downey jr",alts:["robert downey"],c:"Movies & TV"},
{q:"What TV show featured the fictional Dunder Mifflin Paper Company?",a:"the office",alts:["office"],c:"Movies & TV"},
{q:"What is the name of the lion in 'The Lion, the Witch and the Wardrobe'?",a:"aslan",c:"Movies & TV"},
{q:"What animated film features a character called Elsa?",a:"frozen",c:"Movies & TV"},
{q:"In what year was the first Star Wars film released?",a:"1977",c:"Movies & TV"},
{q:"What actor played the Joker in 'The Dark Knight'?",a:"heath ledger",alts:["ledger"],c:"Movies & TV"},
{q:"What show is set in the fictional Westeros?",a:"game of thrones",alts:["got"],c:"Movies & TV"},
{q:"What Pixar film is set in the Mexican Day of the Dead?",a:"coco",c:"Movies & TV"},
{q:"Who directed Pulp Fiction?",a:"tarantino",alts:["quentin tarantino"],c:"Movies & TV"},
{q:"What actress plays Katniss Everdeen in 'The Hunger Games'?",a:"jennifer lawrence",alts:["lawrence"],c:"Movies & TV"},
{q:"What is the name of the main character in 'Breaking Bad'?",a:"walter white",alts:["walt white","heisenberg"],c:"Movies & TV"},
{q:"How many seasons does 'Friends' have?",a:"10",c:"Movies & TV"},

// ── MUSIC ──
{q:"What band performed 'Bohemian Rhapsody'?",a:"queen",c:"Music"},
{q:"What is the name of Taylor Swift's debut album?",a:"taylor swift",c:"Music"},
{q:"Who is known as the 'King of Pop'?",a:"michael jackson",alts:["mj"],c:"Music"},
{q:"What instrument does a percussionist typically play?",a:"drums",alts:["percussion"],c:"Music"},
{q:"What does BPM stand for in music?",a:"beats per minute",c:"Music"},
{q:"Which country is reggae music from?",a:"jamaica",c:"Music"},
{q:"What singer's real name is Robyn Fenty?",a:"rihanna",c:"Music"},
{q:"How many strings does a standard guitar have?",a:"6",alts:["six"],c:"Music"},
{q:"What is the highest female singing voice called?",a:"soprano",c:"Music"},
{q:"What music festival takes place in Glastonbury, England?",a:"glastonbury",alts:["glastonbury festival"],c:"Music"},
{q:"What artist holds the record for the most Grammy wins?",a:"beyonce",c:"Music"},
{q:"Which country is the origin of K-pop?",a:"south korea",alts:["korea"],c:"Music"},
{q:"What does the music term 'forte' mean?",a:"loud",alts:["strong"],c:"Music"},
{q:"What is the name of the frequency at which music is tuned?",a:"440",alts:["440 hz","a440"],c:"Music",h:"Concert A = 440 Hz"},
{q:"What singer is known for the song 'Lose Yourself'?",a:"eminem",c:"Music"},

// ── ART & LITERATURE ──
{q:"Who wrote '1984'?",a:"george orwell",alts:["orwell"],c:"Art & Literature"},
{q:"What is the name of the painting featuring a woman with a mysterious smile?",a:"mona lisa",c:"Art & Literature"},
{q:"Who wrote 'Pride and Prejudice'?",a:"jane austen",alts:["austen"],c:"Art & Literature"},
{q:"What art movement is Salvador Dali associated with?",a:"surrealism",c:"Art & Literature"},
{q:"Who painted the Sistine Chapel ceiling?",a:"michelangelo",c:"Art & Literature"},
{q:"What is the term for a Japanese poem with 17 syllables?",a:"haiku",c:"Art & Literature"},
{q:"What novel begins with 'Call me Ishmael'?",a:"moby dick",alts:["moby-dick"],c:"Art & Literature"},
{q:"Who wrote 'The Alchemist'?",a:"paulo coelho",alts:["coelho"],c:"Art & Literature"},
{q:"What is the literary device of giving human traits to non-human things called?",a:"personification",c:"Art & Literature"},
{q:"Who sculpted 'The Thinker'?",a:"rodin",alts:["auguste rodin"],c:"Art & Literature"},
{q:"What country does the artist Banksy come from?",a:"england",alts:["uk","britain"],c:"Art & Literature"},
{q:"What Shakespeare play features the characters Rosencrantz and Guildenstern?",a:"hamlet",c:"Art & Literature"},
{q:"Who wrote 'The Divine Comedy'?",a:"dante",alts:["dante alighieri"],c:"Art & Literature"},
{q:"What Russian author wrote 'Crime and Punishment'?",a:"dostoevsky",alts:["fyodor dostoevsky"],c:"Art & Literature"},
{q:"In what city is the Louvre museum located?",a:"paris",c:"Art & Literature"},

// ── TECHNOLOGY ──
{q:"What does CPU stand for?",a:"central processing unit",c:"Technology"},
{q:"Who co-founded Apple with Steve Jobs?",a:"steve wozniak",alts:["wozniak"],c:"Technology"},
{q:"What does SQL stand for?",a:"structured query language",c:"Technology"},
{q:"What year was the World Wide Web invented?",a:"1989",alts:["1991"],c:"Technology",h:"Invented 1989, publicly available 1991"},
{q:"What is the most popular programming language worldwide?",a:"python",alts:["javascript","java"],c:"Technology"},
{q:"What does RAM stand for?",a:"random access memory",c:"Technology"},
{q:"What company created the Android operating system?",a:"google",c:"Technology"},
{q:"What is the name of Elon Musk's AI company?",a:"xai",alts:["x.ai","grok"],c:"Technology"},
{q:"What does VPN stand for?",a:"virtual private network",c:"Technology"},
{q:"What is the binary representation of the number 8?",a:"1000",c:"Technology"},
{q:"What protocol is used to send emails?",a:"smtp",c:"Technology"},
{q:"What does the 'S' in HTTPS stand for?",a:"secure",c:"Technology"},
{q:"Which company created the programming language Java?",a:"sun microsystems",alts:["oracle","sun"],c:"Technology"},
{q:"What does IoT stand for?",a:"internet of things",c:"Technology"},
{q:"What is the most used web browser in the world?",a:"chrome",alts:["google chrome"],c:"Technology"},

// ── SPACE ──
{q:"How many moons does Mars have?",a:"2",alts:["two"],c:"Space"},
{q:"What is the name of NASA's Mars rover that landed in 2021?",a:"perseverance",c:"Space"},
{q:"How long does light from the sun take to reach Earth?",a:"8",alts:["8 minutes","8.3"],c:"Space",h:"About 8 minutes"},
{q:"What is the largest planet in our solar system?",a:"jupiter",c:"Space"},
{q:"What is a light-year a measure of?",a:"distance",c:"Space"},
{q:"What is the name of the galaxy we live in?",a:"milky way",c:"Space"},
{q:"Who was the first human to walk on the moon?",a:"neil armstrong",alts:["armstrong"],c:"Space"},
{q:"What is the name of the force that prevents objects from escaping a black hole?",a:"gravity",alts:["gravitational pull"],c:"Space"},
{q:"What planet has a day longer than its year?",a:"venus",c:"Space"},
{q:"What is the Hubble Space Telescope named after?",a:"edwin hubble",alts:["hubble"],c:"Space"},
{q:"How many Earth days does it take Mars to orbit the Sun?",a:"687",c:"Space"},
{q:"What was the first animal sent to space?",a:"laika",alts:["dog","laika the dog"],c:"Space"},
{q:"What is the name of the theory that describes the origin of the universe?",a:"big bang",alts:["big bang theory"],c:"Space"},
{q:"What element is most abundant in the Sun?",a:"hydrogen",c:"Space"},
{q:"What planet is known as the 'ice giant'?",a:"neptune",alts:["uranus"],c:"Space"},

// ── HUMAN BODY ──
{q:"What is the longest bone in the human body?",a:"femur",alts:["thigh bone"],c:"Human Body"},
{q:"How many chambers does the human heart have?",a:"4",alts:["four"],c:"Human Body"},
{q:"What is the largest organ in the human body?",a:"skin",c:"Human Body"},
{q:"What organ produces bile?",a:"liver",c:"Human Body"},
{q:"What is the normal human body temperature in Celsius?",a:"37",alts:["37 degrees"],c:"Human Body"},
{q:"How many pairs of cranial nerves does the human brain have?",a:"12",alts:["twelve"],c:"Human Body"},
{q:"What is the smallest bone in the human body?",a:"stapes",alts:["stirrup"],c:"Human Body",h:"It's in the ear"},
{q:"What protein makes hair and nails?",a:"keratin",c:"Human Body"},
{q:"How many teeth does an adult human have?",a:"32",c:"Human Body"},
{q:"What percentage of the human body is water?",a:"60",alts:["60%"],c:"Human Body"},
{q:"What is the name of the fluid surrounding the brain?",a:"cerebrospinal fluid",alts:["csf"],c:"Human Body"},
{q:"What type of blood cell fights infection?",a:"white blood cell",alts:["leukocyte","white cells"],c:"Human Body"},
{q:"How many lobes does the human brain have?",a:"4",alts:["four"],c:"Human Body"},
{q:"What is the scientific name for the kneecap?",a:"patella",c:"Human Body"},
{q:"What gland is known as the 'master gland' of the endocrine system?",a:"pituitary",alts:["pituitary gland"],c:"Human Body"},

// ── LANGUAGES ──
{q:"What does 'Schadenfreude' mean in English?",a:"joy from others misfortune",alts:["pleasure from others pain"],c:"Languages",h:"German word"},
{q:"How do you say 'thank you' in Japanese?",a:"arigatou",alts:["arigato","arigatou gozaimasu"],c:"Languages"},
{q:"What does the Spanish word 'madrugada' mean?",a:"early morning",alts:["dawn","small hours"],c:"Languages"},
{q:"What language has the most speakers in Africa?",a:"swahili",alts:["arabic"],c:"Languages"},
{q:"What does the French phrase 'je ne sais quoi' literally mean?",a:"i don't know what",alts:["i don't know what it is"],c:"Languages"},
{q:"What is the most translated book in the world?",a:"bible",c:"Languages"},
{q:"In Arabic, what does 'inshallah' mean?",a:"god willing",alts:["if god wills it"],c:"Languages"},
{q:"What language has the most words?",a:"english",c:"Languages"},
{q:"What does the Japanese word 'ikigai' mean?",a:"reason for being",alts:["purpose","reason for living"],c:"Languages"},
{q:"How do you say 'goodbye' in Italian?",a:"arrivederci",alts:["ciao","addio"],c:"Languages"},
{q:"What does the Portuguese word 'saudade' describe?",a:"longing",alts:["nostalgia","yearning","melancholy"],c:"Languages",h:"A melancholic longing for something absent"},
{q:"What is the official language of Brazil?",a:"portuguese",c:"Languages"},
{q:"What does 'merci' mean in French?",a:"thank you",c:"Languages"},
{q:"How do you say 'water' in Arabic?",a:"maa",alts:["ma","ma'"],c:"Languages"},
{q:"What does the German word 'Weltschmerz' mean?",a:"world pain",alts:["world weariness","pain of the world"],c:"Languages"},

// ── FINANCE ──
{q:"What does IPO stand for?",a:"initial public offering",c:"Finance"},
{q:"What is the term for a market in which stock prices are rising?",a:"bull market",c:"Finance"},
{q:"What is the world's reserve currency?",a:"us dollar",alts:["dollar","usd"],c:"Finance"},
{q:"What does ETF stand for?",a:"exchange traded fund",c:"Finance"},
{q:"What is compound interest?",a:"interest on interest",alts:["interest earned on principal and accumulated interest"],c:"Finance"},
{q:"What does GDP stand for?",a:"gross domestic product",c:"Finance"},
{q:"What is the currency of Switzerland?",a:"franc",alts:["swiss franc","chf"],c:"Finance"},
{q:"What is the largest stock exchange in the world?",a:"new york stock exchange",alts:["nyse"],c:"Finance"},
{q:"What does ROI stand for?",a:"return on investment",c:"Finance"},
{q:"What is the term for money that is not backed by a physical commodity?",a:"fiat currency",alts:["fiat"],c:"Finance"},
{q:"What is quantitative easing?",a:"central bank money printing",alts:["buying bonds to inject money"],c:"Finance"},
{q:"What is the P/E ratio?",a:"price to earnings",alts:["price earnings ratio"],c:"Finance"},
{q:"What is the term for selling shares you don't own, hoping to buy them back cheaper?",a:"short selling",alts:["shorting"],c:"Finance"},
{q:"What is inflation?",a:"rise in price levels",alts:["prices rising"],c:"Finance"},
{q:"Who founded Berkshire Hathaway?",a:"warren buffett",alts:["buffett"],c:"Finance"},

// ── WORLD FLAGS ──
{q:"Which country's flag has a maple leaf?",a:"canada",c:"World Flags"},
{q:"What country has a flag with a cedar tree?",a:"lebanon",c:"World Flags"},
{q:"Which flag features a crescent moon and star, and is red with white?",a:"turkey",alts:["pakistan"],c:"World Flags"},
{q:"What country has a flag with a sun in the center and red-white-red stripes?",a:"austria",c:"World Flags"},
{q:"Which country's flag is all green?",a:"libya",alts:["saudi arabia"],c:"World Flags",h:"Libya was solid green 1977-2011"},
{q:"What country has a flag with only two colors, red and white, divided horizontally?",a:"poland",alts:["latvia","denmark"],c:"World Flags"},
{q:"What flag features a bald eagle?",a:"mexico",alts:["united states"],c:"World Flags",h:"Mexico's coat of arms features an eagle"},
{q:"Which flag is the only one that is not rectangular?",a:"nepal",c:"World Flags"},
{q:"What does the red circle on Japan's flag represent?",a:"sun",alts:["the sun"],c:"World Flags"},
{q:"Which African country has a flag with a Kalashnikov rifle?",a:"mozambique",c:"World Flags"},

// ── WORLD CAPITALS ──
{q:"What is the capital of Portugal?",a:"lisbon",c:"World Capitals"},
{q:"What is the capital of Indonesia?",a:"jakarta",alts:["nusantara"],c:"World Capitals",h:"Being moved to Nusantara but Jakarta still common"},
{q:"What is the capital of Morocco?",a:"rabat",c:"World Capitals"},
{q:"What is the capital of Nigeria?",a:"abuja",c:"World Capitals"},
{q:"What is the capital of Pakistan?",a:"islamabad",c:"World Capitals"},
{q:"What is the capital of Colombia?",a:"bogota",alts:["bogotá"],c:"World Capitals"},
{q:"What is the capital of Ukraine?",a:"kyiv",alts:["kiev"],c:"World Capitals"},
{q:"What is the capital of Sweden?",a:"stockholm",c:"World Capitals"},
{q:"What is the capital of Ethiopia?",a:"addis ababa",c:"World Capitals"},
{q:"What is the capital of Saudi Arabia?",a:"riyadh",c:"World Capitals"},
{q:"What is the capital of the Philippines?",a:"manila",c:"World Capitals"},
{q:"What is the capital of Peru?",a:"lima",c:"World Capitals"},
{q:"What is the capital of Iran?",a:"tehran",c:"World Capitals"},
{q:"What is the capital of Bangladesh?",a:"dhaka",c:"World Capitals"},
{q:"What is the capital of Chile?",a:"santiago",c:"World Capitals"},

// ── LANDMARKS ──
{q:"In which country is the Taj Mahal located?",a:"india",c:"Landmarks"},
{q:"What city is the Sagrada Familia in?",a:"barcelona",c:"Landmarks"},
{q:"What country is Angkor Wat in?",a:"cambodia",c:"Landmarks"},
{q:"In which city is the Brandenburg Gate?",a:"berlin",c:"Landmarks"},
{q:"Where is the Acropolis located?",a:"athens",alts:["greece"],c:"Landmarks"},
{q:"What ocean is the Bermuda Triangle in?",a:"atlantic",alts:["atlantic ocean"],c:"Landmarks"},
{q:"In which country is the Blue Mosque?",a:"turkey",c:"Landmarks"},
{q:"What US state is the Grand Canyon in?",a:"arizona",c:"Landmarks"},
{q:"The Alhambra palace is in which country?",a:"spain",c:"Landmarks"},
{q:"What city is Big Ben located in?",a:"london",c:"Landmarks"},
{q:"Where is Petra, the ancient city carved into rock?",a:"jordan",c:"Landmarks"},
{q:"The ancient city of Carthage was near which modern city?",a:"tunis",alts:["tunisia","carthage"],c:"Landmarks"},
{q:"In which country is the Blarney Stone?",a:"ireland",c:"Landmarks"},
{q:"What US state is the Statue of Liberty officially in?",a:"new jersey",alts:["new york","ny","nj"],c:"Landmarks"},
{q:"In which city is the Uffizi Gallery?",a:"florence",c:"Landmarks"},

// ── MATH ──
{q:"What is pi to two decimal places?",a:"3.14",c:"Math"},
{q:"What is the sum of angles in a triangle?",a:"180",alts:["180 degrees"],c:"Math"},
{q:"What is 12 factorial?",a:"479001600",c:"Math"},
{q:"What is the derivative of x²?",a:"2x",c:"Math"},
{q:"What is the only even prime number?",a:"2",alts:["two"],c:"Math"},
{q:"What is the square root of 625?",a:"25",c:"Math"},
{q:"What is the next prime after 17?",a:"19",c:"Math"},
{q:"If a triangle has sides 3, 4, and 5 — what type of triangle is it?",a:"right",alts:["right triangle","right-angled"],c:"Math"},
{q:"What is the formula for the area of a circle?",a:"pi r squared",alts:["πr²","pi*r^2"],c:"Math"},
{q:"What is 15% of 200?",a:"30",c:"Math"},
{q:"How many edges does a cube have?",a:"12",alts:["twelve"],c:"Math"},
{q:"What number is 'e' to 2 decimal places?",a:"2.72",alts:["2.71"],c:"Math"},
{q:"What is the Roman numeral for 1000?",a:"m",c:"Math"},
{q:"What is log base 10 of 1000?",a:"3",c:"Math"},
{q:"What is the Fibonacci sequence's 7th number?",a:"13",c:"Math",h:"1,1,2,3,5,8,13..."},

// ── FASHION ──
{q:"What is the fashion house founded by Coco Chanel?",a:"chanel",c:"Fashion"},
{q:"What fashion item did Mary Quant popularize in the 1960s?",a:"miniskirt",alts:["mini skirt"],c:"Fashion"},
{q:"What fabric is made from the hair of an Angora goat?",a:"mohair",c:"Fashion"},
{q:"What is the name of Christian Dior's signature post-WWII silhouette?",a:"new look",alts:["the new look"],c:"Fashion"},
{q:"What luxury brand is known for the double-G logo?",a:"gucci",c:"Fashion"},
{q:"What is fast fashion?",a:"cheap rapidly produced clothing",alts:["mass produced cheap fashion","cheap trendy clothing"],c:"Fashion"},
{q:"What is the name of Virgil Abloh's luxury brand?",a:"off-white",alts:["off white"],c:"Fashion"},
{q:"What material is traditionally used to make a kimono?",a:"silk",c:"Fashion"},
{q:"What luxury brand has the overlapping C logo?",a:"chanel",c:"Fashion"},
{q:"What term describes wearing mixed patterns and textures?",a:"pattern mixing",alts:["mixing prints","print mixing"],c:"Fashion"},
{q:"What is the Pantone Color of the Year 2024?",a:"peach fuzz",alts:["peach"],c:"Fashion"},
{q:"What Italian luxury brand is known for its horse-bit loafer?",a:"gucci",c:"Fashion"},
{q:"What is 'haute couture'?",a:"high fashion custom clothing",alts:["high-end custom fashion","couture"],c:"Fashion"},
{q:"What shoe brand is known for the 'Superstar' sneaker?",a:"adidas",c:"Fashion"},
{q:"What is the oldest French luxury fashion house still operating?",a:"hermes",alts:["hermès"],c:"Fashion"},

// ── PSYCHOLOGY ──
{q:"What is the term for the inability to recognize faces?",a:"prosopagnosia",alts:["face blindness"],c:"Psychology"},
{q:"Who developed the concept of the unconscious mind?",a:"freud",alts:["sigmund freud"],c:"Psychology"},
{q:"What is cognitive dissonance?",a:"mental discomfort from conflicting beliefs",alts:["holding contradictory beliefs"],c:"Psychology"},
{q:"What is the name of Maslow's motivational theory?",a:"hierarchy of needs",alts:["maslow's hierarchy"],c:"Psychology"},
{q:"What is the term for attributing your own thoughts to others?",a:"projection",c:"Psychology"},
{q:"What Stanford experiment studied the psychological effects of becoming a prisoner or guard?",a:"stanford prison experiment",alts:["stanford prison"],c:"Psychology"},
{q:"What is the 'bystander effect'?",a:"people less likely to help when others are present",alts:["diffusion of responsibility"],c:"Psychology"},
{q:"What is confirmation bias?",a:"favoring information that confirms existing beliefs",c:"Psychology"},
{q:"What is the name of Pavlov's most famous experiment subject?",a:"dog",alts:["dogs"],c:"Psychology",h:"He conditioned dogs to salivate at a bell"},
{q:"What does the Rorschach test involve?",a:"inkblots",alts:["ink blot test","ink blots"],c:"Psychology"},
{q:"What is the term for fear of open spaces?",a:"agoraphobia",c:"Psychology"},
{q:"What is the 'halo effect'?",a:"positive bias from one trait affecting overall judgement",alts:["assuming good traits from one good quality"],c:"Psychology"},
{q:"What psychologist proposed the theory of operant conditioning?",a:"skinner",alts:["b.f. skinner","bf skinner"],c:"Psychology"},
{q:"What is gaslighting?",a:"manipulating someone to question their reality",alts:["psychological manipulation"],c:"Psychology"},
{q:"What is the fight-or-flight response triggered by?",a:"stress",alts:["perceived threat","adrenaline"],c:"Psychology"},

// ── MYTHOLOGY ──
{q:"Who is the Greek god of the sun?",a:"apollo",alts:["helios"],c:"Mythology"},
{q:"What is the name of the Norse world tree?",a:"yggdrasil",c:"Mythology"},
{q:"Who is the Egyptian god of the dead?",a:"osiris",alts:["anubis"],c:"Mythology"},
{q:"What creature in Greek mythology had snakes for hair?",a:"medusa",c:"Mythology"},
{q:"What did Prometheus steal from the gods to give to humans?",a:"fire",c:"Mythology"},
{q:"Who is the Roman equivalent of the Greek god Ares?",a:"mars",c:"Mythology"},
{q:"What is the name of the realm of the dead in Norse mythology?",a:"hel",alts:["helheim"],c:"Mythology"},
{q:"What animal is associated with the Hindu god Ganesha?",a:"elephant",c:"Mythology"},
{q:"Who was the first woman in Greek mythology, created by the gods?",a:"pandora",c:"Mythology"},
{q:"What is the name of the giant squid-like sea monster in Norse legend?",a:"kraken",c:"Mythology"},
{q:"Which Greek hero killed the Minotaur?",a:"theseus",c:"Mythology"},
{q:"What does the name 'Zeus' mean?",a:"sky",alts:["shining","sky god"],c:"Mythology"},
{q:"What substance were the Greek gods said to drink?",a:"nectar",alts:["ambrosia"],c:"Mythology"},
{q:"In Roman mythology, who is the god of the sea?",a:"neptune",c:"Mythology"},
{q:"What is the name of Thor's father?",a:"odin",c:"Mythology"},

// ── NATURE ──
{q:"What is the world's largest rainforest?",a:"amazon",alts:["amazon rainforest"],c:"Nature"},
{q:"What process do trees use to transport water from roots to leaves?",a:"transpiration",alts:["capillary action"],c:"Nature"},
{q:"What is the name of the layer of atmosphere that absorbs UV radiation?",a:"ozone layer",alts:["ozone"],c:"Nature"},
{q:"What natural phenomenon is measured by the Richter scale?",a:"earthquakes",alts:["seismic activity"],c:"Nature"},
{q:"What is the term for a region that receives less than 250mm of rain per year?",a:"desert",c:"Nature"},
{q:"What is the name of the hottest recorded place on Earth?",a:"death valley",c:"Nature"},
{q:"What gas is produced during photosynthesis?",a:"oxygen",c:"Nature"},
{q:"What is the deepest point in the ocean?",a:"mariana trench",alts:["challenger deep","mariana"],c:"Nature"},
{q:"What causes the Northern Lights?",a:"solar particles",alts:["solar wind","charged particles from sun"],c:"Nature"},
{q:"What is the scientific term for a shooting star?",a:"meteor",alts:["meteorite","meteoroid"],c:"Nature"},
{q:"How many species of shark are there (approximately)?",a:"500",alts:["over 500","500 species"],c:"Nature"},
{q:"What is the most venomous animal in the world?",a:"box jellyfish",alts:["jellyfish","irukandji jellyfish"],c:"Nature"},
{q:"What percentage of Earth's species live in the ocean?",a:"80",alts:["over 80"],c:"Nature"},
{q:"What is the chemical symbol for the most abundant gas in the atmosphere?",a:"n2",alts:["n","n₂"],c:"Nature"},
{q:"What is a group of wolves called?",a:"pack",c:"Nature"},

// ── CARS & TRANSPORT ──
{q:"What does SUV stand for?",a:"sport utility vehicle",c:"Cars & Transport"},
{q:"What country produces the most cars in the world?",a:"china",c:"Cars & Transport"},
{q:"What does MPG stand for?",a:"miles per gallon",c:"Cars & Transport"},
{q:"What is the fastest production car in the world?",a:"bugatti chiron super sport",alts:["bugatti","ssc tuatara"],c:"Cars & Transport"},
{q:"In which country was the automobile first invented?",a:"germany",c:"Cars & Transport",h:"Karl Benz patented it in Germany, 1886"},
{q:"What does ABS stand for in cars?",a:"anti-lock braking system",alts:["antilock braking"],c:"Cars & Transport"},
{q:"What is the world's best-selling car of all time?",a:"toyota corolla",alts:["corolla"],c:"Cars & Transport"},
{q:"Who founded Tesla?",a:"elon musk",alts:["martin eberhard","marc tarpenning"],c:"Cars & Transport",h:"Founded by Eberhard & Tarpenning, Musk joined as chairman"},
{q:"What is the aerodynamic shape cars are designed to reduce?",a:"drag",alts:["air resistance"],c:"Cars & Transport"},
{q:"What fuel do most commercial airplanes use?",a:"jet fuel",alts:["kerosene","jet a"],c:"Cars & Transport"},
{q:"What does EV stand for in the automotive world?",a:"electric vehicle",c:"Cars & Transport"},
{q:"What is the speed of a knot in km/h (approx)?",a:"1.85",alts:["1.852","about 2"],c:"Cars & Transport"},
{q:"What year was the first iPhone released?",a:"2007",c:"Cars & Transport"},
{q:"What iconic German highway has no speed limit?",a:"autobahn",c:"Cars & Transport"},
{q:"What does NASCAR stand for?",a:"national association for stock car auto racing",alts:["stock car racing"],c:"Cars & Transport"},
];

const GUESS_DATA={
Countries:[
{answer:"Japan",clues:["Island nation in East Asia","Famous for cherry blossoms","Capital is Tokyo","Home of Mount Fuji","Known for anime and sushi"]},
{answer:"Brazil",clues:["Largest South American country","Famous for Carnival","Amazon rainforest","Portuguese-speaking","5 World Cup wins"]},
{answer:"Egypt",clues:["North African country","Home of the Nile","Great Pyramids","Capital is Cairo","Ancient hieroglyphs"]},
{answer:"Switzerland",clues:["Landlocked European country","Famous for chocolate","The Alps","Banking capital","4 official languages"]},
{answer:"Morocco",clues:["North African kingdom","Famous for tagine","Atlantic & Mediterranean coasts","Marrakech medina","Colorful souks and riads"]},
{answer:"India",clues:["Second most populous","Home of Taj Mahal","Bollywood cinema","Curry originated here","22 official languages"]},
{answer:"Australia",clues:["Both country and continent","Home of kangaroos","Sydney Opera House","Outback desert","Great Barrier Reef"]},
{answer:"Mexico",clues:["Southern North America","Famous for tacos","Aztec civilization","Day of the Dead","Cancún beaches"]},
{answer:"South Korea",clues:["East Asian country","Capital is Seoul","K-pop and K-dramas","K-pop originated here","Samsung and Hyundai"]},
{answer:"Iceland",clues:["North Atlantic island","Northern Lights","Geothermal energy","Reykjavik is the capital","Almost no trees"]},
{answer:"Peru",clues:["South American country","Machu Picchu","Inca Empire","Amazon and Andes","Capital is Lima"]},
{answer:"Greece",clues:["Mediterranean country","Ancient civilization","The Acropolis","Birthplace of democracy","Olympic Games origin"]},
],
Animals:[
{answer:"Octopus",clues:["Ocean dweller","Eight limbs","Changes color","Three hearts","Extremely intelligent"]},
{answer:"Elephant",clues:["Largest land animal","Africa and Asia","Has a trunk","Great memory","Lives in herds"]},
{answer:"Penguin",clues:["Flightless bird","Black and white","Great swimmer","Cold climates","Emperor is largest species"]},
{answer:"Chameleon",clues:["Type of lizard","Changes color","Independent eyes","Sticky tongue","Common in Madagascar"]},
{answer:"Dolphin",clues:["Marine mammal","Very intelligent","Echolocation","Lives in pods","Playful nature"]},
{answer:"Flamingo",clues:["Pink bird","Stands on one leg","Lives near water","Color comes from diet","Tropical areas"]},
{answer:"Platypus",clues:["Semi-aquatic mammal","Has a bill like a duck","Lays eggs despite being a mammal","Found in Australia","Males have venomous spurs"]},
{answer:"Narwhal",clues:["Arctic whale","Has a long spiral tusk","Called the 'unicorn of the sea'","Rarely seen","Travels in pods"]},
],
Elements:[
{answer:"Gold",clues:["Symbol Au","Atomic number 79","Precious metal","Doesn't corrode","Jewelry for millennia"]},
{answer:"Oxygen",clues:["Symbol O","21% of atmosphere","Essential for breathing","Atomic number 8","Discovered 1770s"]},
{answer:"Mercury",clues:["Liquid at room temperature","Named after a planet","Symbol Hg","Used in old thermometers","Atomic number 80"]},
{answer:"Carbon",clues:["Atomic number 6","Basis of organic life","Can form diamond","Symbol C","In carbon dioxide"]},
{answer:"Iron",clues:["Symbol Fe","Used to make steel","Most common element on Earth by mass","Atomic number 26","Makes blood red"]},
{answer:"Uranium",clues:["Radioactive element","Used in nuclear power","Atomic number 92","Named after a planet","Silver-grey metal"]},
],
'Famous People':[
{answer:"Cleopatra",clues:["Ancient ruler","Last active pharaoh of Egypt","Famous for her beauty","Allied with Julius Caesar","Egyptian queen"]},
{answer:"Einstein",clues:["Famous physicist","E=mc²","German-born","Won the Nobel Prize","Known for wild hair"]},
{answer:"Shakespeare",clues:["English playwright","Author of Hamlet","Globe Theatre","Born in Stratford-upon-Avon","Romeo and Juliet"]},
{answer:"Napoleon",clues:["French military leader","Conquered much of Europe","Short statured (mostly myth)","Exiled to Elba","Battle of Waterloo"]},
{answer:"Frida Kahlo",clues:["Mexican painter","Known for self-portraits","Married Diego Rivera","Survived serious accident","Unibrow"]},
{answer:"Nikola Tesla",clues:["Serbian-American inventor","AC electricity","Rivaled with Edison","Visionary and eccentric","Tesla company named after him"]},
],
Foods:[
{answer:"Sushi",clues:["Japanese dish","Contains rice","Often raw fish","Served with wasabi","Eaten with chopsticks or hands"]},
{answer:"Pizza",clues:["Italian origin","Round flatbread base","Tomato sauce","Mozzarella cheese","Margherita is classic"]},
{answer:"Croissant",clues:["French pastry","Crescent shape","Buttery layers","Breakfast food","Flaky texture"]},
{answer:"Shawarma",clues:["Middle Eastern street food","Meat cooked on rotating spit","Served in flatbread","Spiced and marinated","Popular in Lebanon and Turkey"]},
{answer:"Ramen",clues:["Japanese noodle dish","Broth-based","Common toppings: egg, nori, bamboo","Originated in China, perfected in Japan","Tonkotsu and shoyu varieties"]},
{answer:"Tagine",clues:["North African dish","Cooked in a conical clay pot","Slow-cooked","Popular in Morocco","Often sweet and savory"]},
],
Sports:[
{answer:"Tennis",clues:["Uses rackets","Net in middle","Love means zero","Wimbledon is major tournament","Played on court"]},
{answer:"Basketball",clues:["Invented by James Naismith","Round ball","10-foot hoop","NBA","5 players per team on court"]},
{answer:"Cricket",clues:["Bat and ball game","Originated in England","Uses wickets","Innings based","Very popular in India"]},
{answer:"Surfing",clues:["Water sport","Uses a board","Originated in Polynesia","Catching waves","Big wave surfing in Hawaii"]},
{answer:"Fencing",clues:["Olympic sport","Uses a sword or épée","Protective mask required","Scoring via touches","French name for the sport"]},
],
Landmarks:[
{answer:"Eiffel Tower",clues:["Built in 1889","Made of iron","Located in Paris","Named after its engineer","Originally meant to be temporary"]},
{answer:"Great Wall",clues:["Over 13,000 miles long","Built over several centuries","Located in China","Stone and packed earth","UNESCO World Heritage Site"]},
{answer:"Colosseum",clues:["Located in Rome","Ancient amphitheater","Used for gladiator fights","Built around 80 AD","Oval in shape"]},
{answer:"Machu Picchu",clues:["Located in Peru","Inca citadel","High in the Andes","15th century construction","Called the Lost City of the Incas"]},
{answer:"Taj Mahal",clues:["Located in India","Built by Shah Jahan","White marble mausoleum","Built for his wife Mumtaz","UNESCO World Heritage Site"]},
],
Instruments:[
{answer:"Piano",clues:["88 keys","Black and white keys","Invented around 1700","Has strings inside","Press keys to play"]},
{answer:"Guitar",clues:["Usually 6 strings","Strumming or plucking","Has a body and neck","Acoustic or electric","Uses frets"]},
{answer:"Violin",clues:["4 strings","Played with a bow","Used in orchestras","Held under the chin","Stradivarius is most famous maker"]},
{answer:"Saxophone",clues:["Brass instrument","Invented by Adolphe Sax","Common in jazz","Played with a reed","Named after its inventor"]},
{answer:"Harp",clues:["Plucked instrument","Triangular frame","Many strings","Often seen in orchestras","Associated with angels and mythology"]},
],
Movies:[
{answer:"Titanic",clues:["1997 film","DiCaprio and Winslet starred","A ship sinks","Rose and Jack","Won 11 Oscars"]},
{answer:"The Lion King",clues:["Disney animated film","Main character is Simba","Set in African savanna","Hakuna Matata","Mufasa dies"]},
{answer:"The Matrix",clues:["1999 sci-fi film","Red pill or blue pill","Keanu Reeves","Simulated reality","Black trenchcoats"]},
{answer:"Inception",clues:["Christopher Nolan film","Dreams within dreams","Leonardo DiCaprio","Spinning top totem","'We need to go deeper'"]},
],
Brands:[
{answer:"Nike",clues:["Swoosh logo","'Just Do It'","Sports brand","Named after Greek goddess of victory","Founded in Oregon"]},
{answer:"Apple",clues:["Tech company","Bitten apple logo","Makes the iPhone","Founded by Steve Jobs","HQ in Cupertino"]},
{answer:"Chanel",clues:["French luxury brand","Double C logo","Founded by Coco Chanel","Famous for Chanel No. 5","Timeless black dress"]},
{answer:"Ferrari",clues:["Italian car brand","Prancing horse logo","Sports cars","Founded by Enzo Ferrari","Red is signature color"]},
],
};

const GUESS_TOPICS=Object.keys(GUESS_DATA);

const N10_DATA={
"African countries":["algeria","angola","benin","botswana","burkina faso","burundi","cameroon","chad","comoros","congo","djibouti","egypt","eritrea","ethiopia","gabon","gambia","ghana","guinea","ivory coast","kenya","lesotho","liberia","libya","madagascar","malawi","mali","mauritania","mauritius","morocco","mozambique","namibia","niger","nigeria","rwanda","senegal","sierra leone","somalia","south africa","south sudan","sudan","tanzania","togo","tunisia","uganda","zambia","zimbabwe"],
"European capitals":["london","paris","berlin","madrid","rome","lisbon","athens","vienna","brussels","amsterdam","copenhagen","stockholm","oslo","helsinki","dublin","prague","warsaw","budapest","bucharest","zagreb","belgrade","sofia","tallinn","riga","vilnius","luxembourg","bern","bratislava","ljubljana","skopje","podgorica","tirana","sarajevo","kyiv","reykjavik","valletta","monaco","andorra"],
"Chemical elements":["hydrogen","helium","lithium","beryllium","boron","carbon","nitrogen","oxygen","fluorine","neon","sodium","magnesium","aluminum","silicon","phosphorus","sulfur","chlorine","argon","potassium","calcium","iron","copper","zinc","silver","gold","mercury","lead","platinum","uranium","titanium","nickel","cobalt","tin","tungsten","chromium","manganese","iodine","bromine","xenon","radon"],
"Dog breeds":["labrador","poodle","bulldog","beagle","husky","rottweiler","boxer","dalmatian","chihuahua","pug","corgi","dachshund","shih tzu","maltese","pitbull","doberman","akita","collie","greyhound","mastiff","spaniel","terrier","retriever","shepherd","schnauzer","samoyed","malinois","bichon","whippet","weimaraner"],
"Fruits":["apple","banana","orange","grape","strawberry","mango","pineapple","watermelon","peach","pear","cherry","plum","kiwi","coconut","lemon","lime","blueberry","raspberry","blackberry","papaya","guava","pomegranate","fig","apricot","lychee","passion fruit","dragonfruit","avocado","cantaloupe","tangerine","nectarine","persimmon","grapefruit","melon"],
"Currencies":["dollar","euro","pound","yen","yuan","rupee","franc","peso","real","won","krona","dirham","dinar","riyal","baht","lira","rand","ringgit","shekel","zloty","ruble","forint","koruna","taka","naira","hryvnia"],
"Car brands":["toyota","honda","ford","bmw","mercedes","audi","volkswagen","tesla","hyundai","kia","nissan","mazda","subaru","volvo","porsche","ferrari","lamborghini","fiat","chevrolet","jeep","lexus","jaguar","bentley","peugeot","renault","citroen","maserati","alfa romeo","rolls-royce","bugatti"],
"Sports":["soccer","basketball","tennis","cricket","rugby","baseball","volleyball","golf","swimming","boxing","hockey","skiing","cycling","wrestling","fencing","archery","badminton","table tennis","surfing","skateboarding","gymnastics","karate","judo","taekwondo","rowing","handball","squash","polo","lacrosse","water polo"],
"Musical instruments":["piano","guitar","violin","drums","flute","trumpet","saxophone","cello","harp","clarinet","trombone","oboe","bassoon","ukulele","banjo","accordion","harmonica","mandolin","sitar","tabla","xylophone","tuba","viola","bass guitar","synthesizer"],
"Types of pasta":["spaghetti","penne","fusilli","rigatoni","lasagna","ravioli","tortellini","fettuccine","macaroni","linguine","tagliatelle","farfalle","orzo","gnocchi","cannelloni","pappardelle","bucatini","orecchiette","ziti","angel hair","rotini","conchiglie"],
"Countries in Asia":["china","japan","india","south korea","indonesia","vietnam","thailand","pakistan","bangladesh","malaysia","philippines","cambodia","myanmar","nepal","sri lanka","uzbekistan","Kazakhstan","azerbaijan","georgia","mongolia","laos","bhutan","maldives","brunei","east timor"],
"Planets in our solar system":["mercury","venus","earth","mars","jupiter","saturn","uranus","neptune"],
"Languages by speakers":["mandarin","spanish","english","hindi","arabic","portuguese","french","russian","swahili","japanese","urdu","german","korean","turkish","italian","vietnamese","persian","polish","dutch","thai"],
"US States":["california","texas","florida","new york","pennsylvania","illinois","ohio","georgia","north carolina","michigan","new jersey","virginia","washington","arizona","massachusetts","tennessee","indiana","maryland","colorado","minnesota","wisconsin","missouri","alabama","south carolina","louisiana","kentucky","oregon","oklahoma","connecticut","utah"],
};

const N10_CATS=Object.keys(N10_DATA);

const FACES_LIST=['😎','🤓','😤','🥶','🔥','💀','👻','🤖','🦊','🐱','🦁','🐸','🎃','👽','🧠','💎','⚡','🌙','🦋','🐙','🍕','🎯','🎲','🎭'];
const AVB_LIST=['linear-gradient(135deg,#ff2d6a,#a75fff)','linear-gradient(135deg,#5b8cff,#00dda8)','linear-gradient(135deg,#ff7b3a,#ffc640)','linear-gradient(135deg,#a75fff,#5b8cff)','linear-gradient(135deg,#ff4040,#ff7b3a)','linear-gradient(135deg,#00dda8,#5b8cff)','linear-gradient(135deg,#ffc640,#ff2d6a)','linear-gradient(135deg,#30d880,#00dda8)'];
function randomAvatar(){return{f:FACES_LIST[Math.floor(Math.random()*FACES_LIST.length)],b:AVB_LIST[Math.floor(Math.random()*AVB_LIST.length)]};}
